### ISSUE TITLE
Utilização de um Fragment

### ISSUE THREAD

**Issue by rafaelcanovas** [chatakeyama/desafio-telavita#1]
https://github.com/chatakeyama/desafio-telavita/blob/d84861e51d3a411a0bf2147c822412c82275832c/src/components/Header.tsx#L7-L12

Boa noite Camila, tudo bem?

Percebi que optou pela utilização de um Fragment.

Qual é a função de um Fragment e porque optou por utiliza-lo neste caso?

Obrigado :)

**Comment by chatakeyama** [comment]
Olá!

Geralmente sempre coloco o fragment quando estou criando um componente, sem antes saber se vai precisar mesmo,  mais para deixar preparado no caso que realmente precisar e então facilitar um pouco, já que o fragment não prejudica o compoente/aplicação quando usado. Entendo que nesse caso não era necessário usar o fragment, já que o componente StyleHeader acrescenta um nó pai. 
O fragment serve para ajudar nos casos em que o componente tem nós irmãos de html, no mesmo nível e não possuem um nó pai. Quando usado, cria um nó pai invisível, sem acrescentar nenhum elemento adicional no DOM e por isso não prejudica (acrescentando código extra desnecessário).

**Comment by rafaelcanovas** [comment]
Obrigado Camila!
