### ISSUE TITLE
Styled components

### ISSUE THREAD

**Issue by rafaelcanovas** [chatakeyama/desafio-telavita#3]
https://github.com/chatakeyama/desafio-telavita/blob/42ab641de872e8c8b086f4b38ced77bb78fb9e82/src/components/Card.tsx#L23

Boa noite Camila, tudo bem?

Percebi que neste caso escolheu não criar um componente novo (ex: `<ImageContainer>`) e definiu os estilos diretamente no componente pai:

https://github.com/chatakeyama/desafio-telavita/blob/42ab641de872e8c8b086f4b38ced77bb78fb9e82/src/components/styles/Card.styled.js#L49

Qual foi a motivação desta sua escolha e como ela beneficia a aplicação?

Obrigado :)

**Comment by chatakeyama** [comment]
Olá!

Escolhi não criar um componente para a imagem porque eu sabia que nesse projeto ele não seria reutilizado em nenhum outro lugar da aplicação e não valeria o esforço. Acredito que nesse caso fica mais simples do que criar um componente a mais, um arquivo a mais, um nível/camada a mais. Se o componente da imagem fosse mais complexo e adicionasse muito código específico aí valeria a pena extrair para um novo componente.    

Em relação aos estilos, esta foi a primeira vez que usei o styled-components e nesse caso usei o modo que eu aprendi (com className)  por eu ainda estar em fase de entendimento do uso dessa lib. Eu diria que me falta um pouco mais de prática no uso do styled-components para eu saber melhor como e onde usar.
Olhando novamente o código, vi que talvez ficaria melhor se tivesse um componente de estilo para a imagem, para separar melhor os estilos de cada componente.

**Comment by rafaelcanovas** [comment]
Obrigado Camila!
