### ISSUE TITLE
Múltiplas rotas

### ISSUE THREAD

**Issue by rafaelcanovas** [chatakeyama/desafio-telavita#4]
https://github.com/chatakeyama/desafio-telavita/blob/cc44925288c7e65ab30f6b4fa675f9ea299e35c6/src/App.tsx#L50-L65

Boa tarde Camila, tudo bem?

Caso essa aplicação tivesse o requisito de servir múltiplas páginas em URLs diferentes, que ferramentas teria escolhido para alcançar isto?

Obrigado :)

**Comment by chatakeyama** [comment]
Olá!

Nesta aplicação eu teria usado o react-router-dom porque é uma lib que é muito utilizada pelo que percebi nos meus estudos com React. Então acredito que deve atender bem e se eu precisar de alguma ajuda vou encontrar bastante material de apoio na internet.

**Comment by rafaelcanovas** [comment]
Obrigado Camila!
