### ISSUE TITLE
Comunicação com a API

### ISSUE THREAD

**Issue by rafaelcanovas** [chatakeyama/desafio-telavita#5]
https://github.com/chatakeyama/desafio-telavita/blob/080c7bddf959e7960014aabd1c08b2f2f05cd250/src/services/HttpService.ts#L1-L13

Boa tarde Camila, tudo bem?

Caso tivéssemos que buscar diversos recursos diferentes, com métodos diferentes, de uma mesma API, por exemplo:
- GET https://kitsu.io/api/edge/characters (buscar personagem)
- POST https://kitsu.io/api/edge/characters (criar personagem)
- GET https://kitsu.io/api/edge/characters/algum-personagem/ (buscar mais detalhes de um personagem)
- GET https://kitsu.io/api/edge/animes (buscar animes)

Como considera que seria a melhor forma de arquitetar e possibilitar isto?

Obrigado :)

**Comment by chatakeyama** [comment]
Olá!

Eu criaria um um service (HttpService.ts) onde eu colocaria tudo o que for relacionado ao axios e faria um export para cada método (GET, POST, etc), por exemplo:

export default {
  get: axios.get,
  post: axios.post	
 (...)
}

Em seguida, eu criaria um outro service que chamaria as funções desse HttpService, por exemplo:

import http from './HttpService'
(...)
async function getAll(): Promise<...>{
   ... 
   http.get(api)
   ...
}

Acho que dessa forma ficaria fácil se depois eu quisesse trocar a lib axios por uma outra (teria que alterar em um lugar só). E também eu criaria um service pra cada tipo (anime, charactere).

**Comment by rafaelcanovas** [comment]
Obrigado Camila!
