### ISSUE TITLE
Importação de imagens

### ISSUE THREAD

**Issue by rafaelcanovas** [chatakeyama/desafio-telavita#6]
https://github.com/chatakeyama/desafio-telavita/blob/faded397e18fe617dc6eb0d9a0e1a415aae97ab2/src/components/Pagination.tsx#L54

Boa tarde Camila, tudo bem?

É desejável que, como pessoas engenheiras de software, sejamos avisadas sobre quaisquer problemas antes que eles afetem nossos usuários.

Pensando nisto, como poderíamos garantir que sejamos avisadas caso alguém delete acidentalmente essa imagem da pasta `assets/`?

Obrigado :)

**Comment by chatakeyama** [comment]
Olá!

Para garantir que a imagem permaneça, sem o risco de apagarem acidentalmente, acredito que precisaria ter testes automatizados que façam essa verificação, ou seja, se a imagem existe nesse diretório. Na esteira de CI, os testes quebrariam e  não seria possível lançar uma versão sem a imagem.

**Comment by rafaelcanovas** [comment]
Obrigado Camila!
